config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|fr/ do
    get '/preferences', to: 'preferences#index', as: "preferences"
    get '/preferences/interests', to: 'interests#index', as: "preferences_interests"
    put '/preferences/interests', to: 'interests#edit', as: "edit_preferences_interests"
    get '/preferences/places', to: 'places#index', as: "preferences_places"
    put '/preferences/places', to: 'places#edit', as: "edit_preferences_places"

    get '/privacy-policy', to: 'privacy#index', as: "privacy_policy"
    get '/credits', to: 'credits#index', as: "credits"

    # devise_for :users
    devise_scope :user do
      get "/login" => "devise/sessions#new" # custom path to login/sign_in
      get "/signup" => "devise/registrations#new", as: "signup" # custom path to sign_up/registration
      get "/preferences/account" => "devise/registrations#edit", as: "preferences_account" # custom path to sign_up/registration
    end
    devise_for :users, controllers: { registrations: "registrations" }, path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'confirmation', unlock: 'unlock', registration: 'register', sign_up: 'sign_up' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root 'homepage#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_and_belongs_to_many :users

  # validates :name, uniqueness: { case_sensitive: false }
  validates :name, uniqueness: { case_sensitive: false,
    scope: :user_id }, length: { minimum: 2 }
end

app/models/place.rb
class Place < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :interests, through: :users

  validates :osm_id, uniqueness: { case_sensitive: false }
  validates :osm_id, :name, :address, :latitude, :longitude, presence: true
end

app/models/user.rb
require 'json'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :trackable, :validatable

  has_and_belongs_to_many :interests
  has_and_belongs_to_many :places

  validates :username, uniqueness: { case_sensitive: false }, length: { minimum: 2 }
  validates_associated :interests
  validates_associated :places

  accepts_nested_attributes_for :interests
  accepts_nested_attributes_for :places

  def interests_list=value
    if value.empty?
      raise ArgumentError, 'Please add at least one interest'
    end
    inputted_interests = value.split(',')
      .collect { |interest| interest.strip.downcase }
      .uniq
      .reject { |interest| interest.empty? }
    user_interests = []
    inputted_interests.each do |interest|
      user_interests << Interest.find_or_create_by(name: interest)
    end
    self.interests = user_interests
  end

  def interests_list
    self.interests.collect{|interest| interest.name}.join(', ')
  end

  def places_list=value
    if value.empty?
      raise ArgumentError, 'Please add at least one place'
    end
    inputted_places = JSON.parse(value)
    puts "currents place: #{inputted_places}"
    user_places = []

    # Filter out places which are not precise enough
    inputted_places = filter_places(inputted_places)

    inputted_places.each do |place|
      place['name'] = place['label'].split(',')[0] unless place['name']
      place['address'] = place['label'] unless place['address']
      place['latitude'] = place['y'].to_f unless place['latitude']
      place['longitude'] = place['x'].to_f unless place['longitude']
      place['osm_id'] = place['raw']['osm_id'].to_i unless place['osm_id']
      puts "2.this place: #{place}"
      user_places << Place.create_with(name: place['name'],
                                       address: place['address'],
                                       latitude: place['latitude'],
                                       longitude: place['longitude'])
        .find_or_create_by(osm_id: place['osm_id'])
    end
    self.places = user_places
  end

  def filter_places(inputted_places)
    inputted_places.reject do |place|
      place = place['raw'] if place.has_key?("raw")
      place['type'] == 'city' || place['type'] == 'administrative' || place['osm_type'] == 'relation'
    end
  end

  def places_list
    self.places.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def default_url_options
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = params[:locale] || http_accept_language.compatible_language_from(I18n.available_locales) || I18n.default_locale
  end

  rescue_from ArgumentError do |exception|
     flash.now[:alert] = "Arguments for your request are incorrect"
     redirect_to root_url, :alert => exception.message
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :first_name, :last_name, :interests_list, :places_list])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :interests_list, :places_list])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :interests_list, :places_list])
  end

  def after_sign_in_path_for(resource)
    preferences_path
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def index
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping,
    :user_signed_in, :current_user

  def index
    @interests_sample = Interest.limit(10)
    @all_places = Place.all
    gon.places = @all_places.collect do |place|
      interests = place.interests.collect { |interest| interest.name }
      {interests: interests.uniq,
      place: place}
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping,
    :user_signed_in, :current_user
  before_action :authenticate_user!

  def index
    @interests_sample = Interest.where.not(name: current_user.interests.collect{|interest| interest.name})
      .order(updated_at: :desc).limit(10)
  end

  def edit
    current_user.interests_list = interests_params['interests_list']
    redirect_to preferences_path
  end

  private

  def interests_params
    params.require(:user).permit(:interests_list)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping,
    :user_signed_in, :current_user
  before_action :authenticate_user!

  def index
    @all_places = Place.all
    gon.places = @all_places.collect do |place|
      interests = place.interests.collect { |interest| interest.name }
      {interests: interests.uniq,
      place: place}
    end
  end

  def edit
    current_user.places_list = places_params['places_list']
    redirect_to preferences_path
  end

  private

  def places_params
    params.require(:user).permit(:places_list)
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  helper_method :resource_name, :resource, :devise_mapping,
    :user_signed_in, :current_user
  before_action :authenticate_user!

  def index
    @interests = current_user.interests
    @places = current_user.places
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(resource)
    login_path
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/credits/index.html.erb
<% if flash[:notice] %>
  <div class="flash notice"><i class="fa fa-info-circle" aria-hidden="true"></i><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert"><i class="fa fa-exclamation-circle" aria-hidden="true"></i><%= flash[:alert] %></div>
<% end %>

<div id="credits-section">
  <h2><%=t 'credits.title' %></h2>
  <p><%=t 'credits.description' %></p>
  <ol>
    <li><%=t 'credits.picture_illustration_html' %></li>
    <li><%=t 'credits.font_title_html' %></li>
    <li><%=t 'credits.font_body_html' %></li>
    <li><%=t 'credits.font_awesome_html' %></li>
    <li><%=t 'credits.icon_email_html' %></li>
    <li><%=t 'credits.icon_shop_html' %></li>
    <li><%=t 'credits.icon_eye_html' %></li>
  </ol>
</div>

app/views/homepage/index.html.erb
<div id="welcome-section">
  <h1><%=t 'homepage.welcome.phrase_html' %></h1>
  <%= link_to t("homepage.signup.button"), signup_path, class: "signup-button" %>
  <div class="account-deletion-highlight">(<%=t 'homepage.welcome.account_deletion_highlight' %> <%= link_to t("homepage.welcome.any_moment"), privacy_policy_path %>)</div>
</div>

<div id="explanation-section">
  <h2><%=t 'homepage.explanation.title' %></h2>
  <div id="explanation-container">
    <div>
      <img src="<%= image_path 'noun_email.png' %>"/>
      <p><%=t 'homepage.explanation.email' %></p>
    </div>
    <div>
      <img src="<%= image_path 'noun_cafe.png' %>"/>
      <p><%=t 'homepage.explanation.place' %></p>
    </div>
    <div>
      <img src="<%= image_path 'noun_privacy.png' %>"/>
      <p><%=t 'homepage.explanation.privacy' %></p>
    </div>
  </div>
</div>

<div id="signup-section">
  <h3>1. <%=t 'homepage.signup.title' %></h3>
  <p><%=t 'homepage.signup.description' %></p>
  <p><%=t 'homepage.signup.call_for_button' %></p>
  <%= link_to t("homepage.signup.button"), signup_path, class: "signup-button" %>
</div>

<div id="interests-section">
  <h3>2. <%=t 'homepage.interests.title' %></h3>
  <p><%=t 'homepage.interests.description_html' %></p>
  <ul id="interests-list">
    <% @interests_sample.each do |interest| %>
      <li><%= interest.name %></li>
    <% end %>
  </ul>
</div>

<div id="places-section">
  <h3>3. <%=t 'homepage.places.title' %></h3>
  <p><%=t 'homepage.places.description' %></p>
  <p><%=t 'homepage.places.search_helper' %></p>
  <div id="mapid">
    <p class="map-loading">The map has not been loaded</p>
  </div>
</div>

<div id="socialize-section">
  <h3>4. <%=t 'homepage.socialize.title' %></h3>
  <p><%=t 'homepage.socialize.description_html' %></p>
</div>

<%= link_to t("homepage.signup.button"), signup_path, id: "signup-button-bottom" %>

app/views/interests/index.html.erb
<div id="interests-section">
  <%= form_for(current_user, url: edit_preferences_interests_path, html: { method: :put }) do |f| %>
    <% if flash[:notice] %>
      <div class="flash notice"><i class="fa fa-info-circle" aria-hidden="true"></i><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="flash alert"><i class="fa fa-exclamation-circle" aria-hidden="true"></i><%= flash[:alert] %></div>
    <% end %>

    <h3><%=t 'interests.title' %></h3>
    <p><%=t 'interests.description_html' %></p>
    <%= f.label :interests %><br />
    <%= f.text_field :interests_list, placeholder: "ecology, open source, rock music..." %>

    <p><%=t 'interests.interests_picking' %></p>
    <ul id="interests-list">
      <% @interests_sample.each do |interest| %>
        <li><%= interest.name %></li>
      <% end %>
    </ul>

    <div class="buttons-line">
      <%= link_to(t('preferences.button.back'), preferences_path, class: "button back") %>
      <%= f.submit t 'interests.add_button', class: "form-submit" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kamo.social</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" property="description" content="Meet people with the same interests as you. :)" />
    <meta name="twitter:card" property="twitter:card" content="summary" />
    <meta name="twitter:site" property="twitter:site" content="@KillianKemps" />
    <meta name="twitter:title" property="twitter:title" content="Kamo.social" />
    <meta name="twitter:description" property="twitter:description" content="Meet people with the same interests as you. :)" />
    <meta name="og:title" property="og:title" content="Kamo.social" />
    <meta name="og:type" property="og:type" content="website" />
    <meta name="og:url" property="og:url" content="http://kamo.social" />
    <meta name="og:description" property="og:description" content="Meet people with the same interests as you. :)" />

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'leaflet', media: 'all' %>
    <%= javascript_include_tag 'leaflet' %>
  </head>

  <body>
    <div id="container">
      <%= render "shared/header" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <%= include_gon %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/places/index.html.erb
<div id="places-section">
  <%= form_for(current_user, url: edit_preferences_places_path, html: { method: :put }) do |f| %>
    <% if flash[:notice] %>
      <div class="flash notice"><i class="fa fa-info-circle" aria-hidden="true"></i><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="flash alert"><i class="fa fa-exclamation-circle" aria-hidden="true"></i><%= flash[:alert] %></div>
    <% end %>
    <h3><%=t 'places.title' %></h3>
    <p><%=t 'places.description' %></p>
    <p><%=t 'places.search_helper_html' %></p>
    <p><%=t 'places.caution' %></p>
    <%= f.hidden_field :places_list %>
    <div id="mapid">
      <p class="map-loading">The map has not been loaded</p>
    </div>
    <ul id="added-places">
    </ul>
    <div class="buttons-line">
      <%= link_to(t('preferences.button.back'), preferences_path, class: "button back") %>
      <%= f.submit t 'interests.add_button', class: "form-submit" %>
    </div>
  <% end %>
</div>

app/views/preferences/index.html.erb
<% if flash[:notice] %>
  <div class="flash notice"><i class="fa fa-info-circle" aria-hidden="true"></i><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert"><i class="fa fa-exclamation-circle" aria-hidden="true"></i><%= flash[:alert] %></div>
<% end %>

<p id="preferences-message">
  <% if @interests.empty? || @places.empty? %>
    <%=t 'preferences.message.should_add' %>
  <% else %>
    <%=t 'preferences.message.wait' %>
  <% end %>
</p>

<div id="interests-section">
  <h3><%=t 'preferences.interests.title' %></h3>
  <ul id="interests-list">
    <% @interests.each do |interest| %>
      <li><%= interest.name %></li>
    <% end %>
  </ul>
  <% if @interests.empty? %>
    <%=t 'preferences.interests.empty' %>
  <% end %>
  <%= link_to t("preferences.interests.edit"), preferences_interests_path, class: "button main" %>
</div>

<div id="places-section">
  <h3><%=t 'preferences.places.title' %></h3>
  <ul id="added-places">
    <% @places.each do |place| %>
      <li><span class="name"><%= place.name %></span> <%= place.address %></li>
    <% end %>
  </ul>
  <% if @places.empty? %>
    <%=t 'preferences.places.empty' %>
  <% end %>
  <%= link_to t("preferences.places.edit"), preferences_places_path, class: "button main" %>
</div>

<div id="account-section">
  <h3><%=t 'preferences.account.title' %></h3>
  <%=t 'preferences.account.description' %>
  <%= link_to t("preferences.account.edit"), preferences_account_path, class: "button main" %>
</div>

app/views/privacy/index.html.erb
<% if flash[:notice] %>
  <div class="flash notice"><i class="fa fa-info-circle" aria-hidden="true"></i><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert"><i class="fa fa-exclamation-circle" aria-hidden="true"></i><%= flash[:alert] %></div>
<% end %>

<div id="privacy-section">
  <h1><%=t 'privacy.title' %></h1>

  <h2><%=t 'privacy.summary.title' %></h2>
  <ol>
    <li><%=t 'privacy.summary.storage' %></li>
    <li><%=t 'privacy.summary.change' %></li>
    <li><%=t 'privacy.summary.user_change' %></li>
    <li><%=t 'privacy.summary.guarantee' %></li>
  </ol>

  <h2><%=t 'privacy.general_information.title' %></h2>
  <p><%=t 'privacy.general_information.editor' %> <a href="http://mastodon.qowala.org/@KillianKemps">Killian Kemps</a>.</p>
  <p><%=t 'privacy.general_information.guarantee' %></p>

  <h2><%=t 'privacy.hosting.title' %></h2>
  <p>
    <%=t 'privacy.hosting.hoster' %> <a href="https://www.heroku.com/about">Heroku</a>.<br>
    <%=t 'privacy.hosting.servers' %><br>
    <%=t 'privacy.hosting.address' %><br>
    <address>
      Salesforce<br>

      The Landmark @ 1 Market St.<br>
      Suite 300<br>
      San Francisco, CA<br>
      94105<br>
    </address>
  </p>

  <h2><%=t 'privacy.email.title' %></h2>
  <p>
    <%=t 'privacy.email.provider_html' %><br>
    <%=t 'privacy.email.gdpr_html' %><br>
  </p>

  <h2><%=t 'privacy.personal_data_process.title' %></h2>
  <p><%=t 'privacy.personal_data_process.protection' %></p>
  <p><%=t 'privacy.personal_data_process.rights' %></p>

  <h3><%=t 'privacy.collected_data.title' %></h3>
  <p class="bold"><%=t 'privacy.collected_data.no_commercial_use' %></p>
  <p><%=t 'privacy.collected_data.explicit_data' %></p>
  <ul>
    <li><%=t 'privacy.collected_data.email' %></li>
    <li><%=t 'privacy.collected_data.username' %></li>
    <li><%=t 'privacy.collected_data.password' %></li>
    <li><%=t 'privacy.collected_data.interests' %></li>
    <li><%=t 'privacy.collected_data.places' %></li>
  </ul>

  <p><%=t 'privacy.collected_data.framework_data' %></p>
  <p><%=t 'privacy.collected_data.security_data' %></p>
  <ul>
    <li><%=t 'privacy.collected_data.nb_connections' %></li>
    <li><%=t 'privacy.collected_data.current_open_date' %></li>
    <li><%=t 'privacy.collected_data.last_open_date' %></li>
    <li><%=t 'privacy.collected_data.current_IP' %></li>
    <li><%=t 'privacy.collected_data.last_IP' %></li>
    <li><%=t 'privacy.collected_data.confirmation_date' %></li>
    <li><%=t 'privacy.collected_data.email_confirmation_date' %></li>
    <li><%=t 'privacy.collected_data.creation_date' %></li>
    <li><%=t 'privacy.collected_data.update_date' %></li>
  </ul>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <ul class="conditions">
    <li><%= link_to t("footer.privacy_policy"), privacy_policy_path %></li><!--
    --><li><%= link_to t("footer.credits"), credits_path %></li><!--
    --><li><a href="https://github.com/Kamosocial/kamosocial"><%=t("footer.opensource") %></a></li>
  </ul>
  <ul class="author">
    <li><%=t 'footer.made_with_love' %></li><!--
    --><li>© 2018 <a href="http://mastodon.qowala.org/@KillianKemps">Killian Kemps</a></li>
  </ul>
</div>

app/views/shared/_header.html.erb
<header>
  <div id="logo"><a href="/<%= locale %>">Kamo.social</a></div>
  <div id="lang-dropdown">
    <% if locale.to_s == 'en' %>
      English
    <% elsif locale.to_s == 'fr' %>
      Français
    <% end %>
    <i class="fa fa-sort-desc" aria-hidden="true"></i>
    <ul>
      <li><%= link_to "English", { :locale=>'en' } %></li>
      <li><%= link_to "Français", { :locale=>'fr' } %></li>
    </ul>
  </div>
  <% if user_signed_in? %>
    <div id="session-dropdown">
      <%= current_user.username %>
      <ul>
        <li>
         <%= link_to(t('header.preferences'), preferences_path) %>
         <%= link_to(t('header.logout'), destroy_user_session_path, method: :delete) %>
        </li>
      </ul>
    </div>
  <% else %>
    <%= link_to t('header.login'), login_path, id:"login-button" %>
  <% end %>
</header>

app/views/terms/index.html.erb
<% if flash[:notice] %>
  <div class="flash notice"><i class="fa fa-info-circle" aria-hidden="true"></i><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert"><i class="fa fa-exclamation-circle" aria-hidden="true"></i><%= flash[:alert] %></div>
<% end %>

<div id="terms-section">
  <h2>Résumé</h2>
  <ol>
    <li>Les utilisateurs doivent accepter les conditions d'utilisation avant de s'inscrire</li>
    <li>L'éditeur de Kamo.social ne propose aucune garantie de service et de sécurité compte-tenu de ses faibles moyens.</li>
    <li>Le service peut-être arrêté à tout instant sans notification à ses utilisateurs.</li>
    <li>L'éditeur de Kamo.social se dégage de toute responsabilité de tout effet dû à l'utilisation du site web par ses utilisateurs.</li>
    <li>Le service proposé à ses utilisateurs est gratuit mais des offres payantes pourront être proposées.</li>
    <li>Les utilisateurs peuvent à tout moment s'inscrire ou se désincrire du service sans aucun engagement.</li>
    <li>Les utilisateurs seront notifiés des changements de ces conditions d'utilisation par email.</li>
    <li>Kamo.social se veut une expérimentation du développement du service avec la communauté mais sans être open source.</li>
    <li>Il est possible que Kamo.social ouvre son code source.</li>
  </ol>

  <h2>Prix</h2>
  <p>
  Kamo.social propose une offre gratuite pour ses utilisateurs. L'idée est de maintenir les coûts techniques suffisamment bas pour que l'éditeur puisse continuer à proposer le service gratuitement.<br>
  </p>
  <p>
  Parmi les moyens possibles pour réduire les coûts nous pouvons compter : des choix de serveurs à bas prix, une décentralisation du stockage des données, une décentralisation des outils de calculs.<br>
  </p>
  <p>
  Si les coûts restent trop élevés, l'éditeur peut à tout moment mettre en place des campagnes de dons ou tout autre source de financement afin d'aider à maintenir le service.
  </p>
</div>